/**
 * Curated entry points into the largest open-weight models available as GGUF.
 *
 * The repository ids are starting points, not a source of truth: file lists and
 * sizes are always read live from the Hugging Face API, so a moved or renamed
 * repo surfaces as an error the user can see rather than as stale metadata.
 *
 * `activeParamsB` is what makes these usable at all. A Mixture-of-Experts model
 * only touches a fraction of its weights per token, and that fraction — not the
 * total — determines how much data must move per token.
 */

export type SizeClass = 'gigante' | 'grande' | 'medio' | 'piccolo';

export interface CatalogEntry {
  id: string;
  name: string;
  publisher: string;
  /** Total parameters in billions. */
  totalParamsB: number;
  /** Parameters actually used per token; equals total for dense models. */
  activeParamsB: number;
  architecture: 'dense' | 'moe';
  contextLength: number;
  /** Hugging Face repositories known to publish GGUF conversions. */
  ggufRepos: string[];
  license: string;
  notes: string;
  /** Grouping for the UI, derived from total size rather than capability. */
  sizeClass: SizeClass;
  /** Free-form capability hints used for filtering. */
  tags: string[];
}

export const MODEL_CATALOG: CatalogEntry[] = [
  // ---------------------------------------------------------------------
  // Giganti (> 200B totali) — richiedono streaming da storage
  // ---------------------------------------------------------------------
  {
    id: 'kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    publisher: 'Moonshot AI',
    totalParamsB: 1000,
    activeParamsB: 32,
    architecture: 'moe',
    contextLength: 262144,
    ggufRepos: ['unsloth/Kimi-K2-Thinking-GGUF'],
    license: 'Modified MIT',
    notes: 'Variante con ragionamento esteso: 1T totali, 32B attivi per token.',
    sizeClass: 'gigante',
    tags: ['reasoning', 'agentic'],
  },
  {
    id: 'kimi-k2',
    name: 'Kimi K2 Instruct',
    publisher: 'Moonshot AI',
    totalParamsB: 1000,
    activeParamsB: 32,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/Kimi-K2-Instruct-GGUF', 'ubergarm/Kimi-K2-Instruct-GGUF'],
    license: 'Modified MIT',
    notes: '1T parametri totali ma solo 32B attivi per token: il candidato migliore per lo streaming da storage.',
    sizeClass: 'gigante',
    tags: ['agentic', 'coding'],
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    publisher: 'DeepSeek',
    totalParamsB: 671,
    activeParamsB: 37,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/DeepSeek-R1-GGUF', 'unsloth/DeepSeek-R1-0528-GGUF'],
    license: 'MIT',
    notes: 'Il modello di ragionamento aperto di riferimento. Genera molti token di pensiero, quindi la velocità conta il doppio.',
    sizeClass: 'gigante',
    tags: ['reasoning'],
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    publisher: 'DeepSeek',
    totalParamsB: 671,
    activeParamsB: 37,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/DeepSeek-V3-0324-GGUF', 'MaziyarPanahi/DeepSeek-V3-0324-GGUF'],
    license: 'DeepSeek License',
    notes: '671B totali, 37B attivi. Q4 occupa circa 380 GB su disco.',
    sizeClass: 'gigante',
    tags: ['general'],
  },
  {
    id: 'deepseek-v3.1',
    name: 'DeepSeek V3.1',
    publisher: 'DeepSeek',
    totalParamsB: 671,
    activeParamsB: 37,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/DeepSeek-V3.1-GGUF'],
    license: 'MIT',
    notes: 'Aggiornamento di V3 con modalità di ragionamento commutabile.',
    sizeClass: 'gigante',
    tags: ['reasoning', 'general'],
  },
  {
    id: 'qwen3-coder-480b',
    name: 'Qwen3 Coder 480B A35B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 480,
    activeParamsB: 35,
    architecture: 'moe',
    contextLength: 262144,
    ggufRepos: ['unsloth/Qwen3-Coder-480B-A35B-Instruct-GGUF'],
    license: 'Apache 2.0',
    notes: 'Il più capace fra gli aperti orientati al codice. 35B attivi per token.',
    sizeClass: 'gigante',
    tags: ['coding', 'agentic'],
  },
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick 17B 128E',
    publisher: 'Meta',
    totalParamsB: 400,
    activeParamsB: 17,
    architecture: 'moe',
    contextLength: 1048576,
    ggufRepos: ['unsloth/Llama-4-Maverick-17B-128E-Instruct-GGUF'],
    license: 'Llama 4 Community',
    notes: '128 esperti, solo 17B attivi. Multimodale e con contesto da 1M token.',
    sizeClass: 'gigante',
    tags: ['multimodal', 'long-context'],
  },
  {
    id: 'llama-405b',
    name: 'Llama 3.1 405B Instruct',
    publisher: 'Meta',
    totalParamsB: 405,
    activeParamsB: 405,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['MaziyarPanahi/Meta-Llama-3.1-405B-Instruct-GGUF', 'ThomasBaruzier/Meta-Llama-3.1-405B-Instruct-GGUF'],
    license: 'Llama 3.1 Community',
    notes: 'Denso: ogni token richiede TUTTI i pesi. È il caso peggiore per lo streaming da disco.',
    sizeClass: 'gigante',
    tags: ['general'],
  },
  {
    id: 'glm-4.6',
    name: 'GLM 4.6',
    publisher: 'Zhipu AI',
    totalParamsB: 357,
    activeParamsB: 32,
    architecture: 'moe',
    contextLength: 204800,
    ggufRepos: ['unsloth/GLM-4.6-GGUF', 'bartowski/zai-org_GLM-4.6-GGUF'],
    license: 'MIT',
    notes: 'Circa 355B totali con 32B attivi: profilo tipico di un 300B MoE.',
    sizeClass: 'gigante',
    tags: ['coding', 'agentic'],
  },
  {
    id: 'ernie-4.5-300b',
    name: 'ERNIE 4.5 300B A47B',
    publisher: 'Baidu',
    totalParamsB: 300,
    activeParamsB: 47,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/ERNIE-4.5-300B-A47B-PT-GGUF'],
    license: 'Apache 2.0',
    notes: '47B attivi: fra i MoE grandi è uno dei più esigenti in banda.',
    sizeClass: 'gigante',
    tags: ['multilingual'],
  },
  {
    id: 'nemotron-ultra-253b',
    name: 'Llama 3.1 Nemotron Ultra 253B',
    publisher: 'NVIDIA',
    totalParamsB: 253,
    activeParamsB: 253,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['bartowski/nvidia_Llama-3_1-Nemotron-Ultra-253B-v1-GGUF'],
    license: 'NVIDIA Open Model',
    notes: 'Denso da 253B ottenuto per ricerca architetturale su Llama 405B.',
    sizeClass: 'gigante',
    tags: ['reasoning'],
  },
  {
    id: 'qwen3-235b',
    name: 'Qwen3 235B A22B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 235,
    activeParamsB: 22,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/Qwen3-235B-A22B-GGUF', 'unsloth/Qwen3-235B-A22B-Instruct-2507-GGUF'],
    license: 'Apache 2.0',
    notes: 'Il MoE grande più facile da far girare: 22B attivi per token.',
    sizeClass: 'gigante',
    tags: ['reasoning', 'general'],
  },
  {
    id: 'minimax-m2',
    name: 'MiniMax M2',
    publisher: 'MiniMax',
    totalParamsB: 230,
    activeParamsB: 10,
    architecture: 'moe',
    contextLength: 204800,
    ggufRepos: ['unsloth/MiniMax-M2-GGUF'],
    license: 'MIT',
    notes: 'Solo 10B attivi: il rapporto capacità/banda più favorevole fra i giganti.',
    sizeClass: 'gigante',
    tags: ['agentic', 'coding'],
  },

  // ---------------------------------------------------------------------
  // Grandi (70-200B)
  // ---------------------------------------------------------------------
  {
    id: 'dots-llm1',
    name: 'dots.llm1 142B A14B',
    publisher: 'Rednote HiLab',
    totalParamsB: 142,
    activeParamsB: 14,
    architecture: 'moe',
    contextLength: 32768,
    ggufRepos: ['unsloth/dots.llm1.inst-GGUF'],
    license: 'MIT',
    notes: '14B attivi su 142B totali, addestrato senza dati sintetici.',
    sizeClass: 'grande',
    tags: ['general', 'multilingual'],
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large 2411',
    publisher: 'Mistral AI',
    totalParamsB: 123,
    activeParamsB: 123,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['bartowski/Mistral-Large-Instruct-2411-GGUF'],
    license: 'Mistral Research',
    notes: 'Denso da 123B: al limite di ciò che 128 GB di RAM possono contenere in Q4.',
    sizeClass: 'grande',
    tags: ['general', 'multilingual'],
  },
  {
    id: 'gpt-oss-120b',
    name: 'gpt-oss 120B',
    publisher: 'OpenAI',
    totalParamsB: 117,
    activeParamsB: 5.1,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/gpt-oss-120b-GGUF', 'ggml-org/gpt-oss-120b-GGUF'],
    license: 'Apache 2.0',
    notes: '5.1B attivi per token: gira decentemente anche senza tenere tutto in memoria.',
    sizeClass: 'grande',
    tags: ['reasoning', 'agentic'],
  },
  {
    id: 'command-a',
    name: 'Command A 03-2025',
    publisher: 'Cohere',
    totalParamsB: 111,
    activeParamsB: 111,
    architecture: 'dense',
    contextLength: 262144,
    ggufRepos: ['unsloth/c4ai-command-a-03-2025-GGUF', 'bartowski/CohereForAI_c4ai-command-a-03-2025-GGUF'],
    license: 'CC-BY-NC 4.0',
    notes: 'Denso da 111B con contesto 256K. Licenza non commerciale.',
    sizeClass: 'grande',
    tags: ['multilingual', 'rag'],
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout 17B 16E',
    publisher: 'Meta',
    totalParamsB: 109,
    activeParamsB: 17,
    architecture: 'moe',
    contextLength: 1048576,
    ggufRepos: ['unsloth/Llama-4-Scout-17B-16E-Instruct-GGUF'],
    license: 'Llama 4 Community',
    notes: 'Il Llama 4 piccolo: 16 esperti, 17B attivi, contesto dichiarato 10M.',
    sizeClass: 'grande',
    tags: ['multimodal', 'long-context'],
  },
  {
    id: 'glm-4.5-air',
    name: 'GLM 4.5 Air',
    publisher: 'Zhipu AI',
    totalParamsB: 106,
    activeParamsB: 12,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/GLM-4.5-Air-GGUF'],
    license: 'MIT',
    notes: 'Versione compatta di GLM 4.5: 12B attivi, buon compromesso su hardware consumer.',
    sizeClass: 'grande',
    tags: ['coding', 'agentic'],
  },
  {
    id: 'hunyuan-a13b',
    name: 'Hunyuan A13B',
    publisher: 'Tencent',
    totalParamsB: 80,
    activeParamsB: 13,
    architecture: 'moe',
    contextLength: 262144,
    ggufRepos: ['unsloth/Hunyuan-A13B-Instruct-GGUF'],
    license: 'Tencent Hunyuan',
    notes: '13B attivi su 80B, con modalità di ragionamento rapida e lenta.',
    sizeClass: 'grande',
    tags: ['reasoning'],
  },
  {
    id: 'qwen3-next-80b',
    name: 'Qwen3 Next 80B A3B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 80,
    activeParamsB: 3,
    architecture: 'moe',
    contextLength: 262144,
    ggufRepos: ['unsloth/Qwen3-Next-80B-A3B-Instruct-GGUF'],
    license: 'Apache 2.0',
    notes: 'Solo 3B attivi su 80B: il rapporto più estremo del catalogo, ideale per lo streaming.',
    sizeClass: 'grande',
    tags: ['efficient', 'long-context'],
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B Instruct',
    publisher: 'Meta',
    totalParamsB: 70,
    activeParamsB: 70,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/Llama-3.3-70B-Instruct-GGUF', 'bartowski/Llama-3.3-70B-Instruct-GGUF'],
    license: 'Llama 3.3 Community',
    notes: 'Denso da 70B: entra in 48 GB in Q4, lo standard di paragone da anni.',
    sizeClass: 'grande',
    tags: ['general'],
  },
  {
    id: 'qwen2.5-72b',
    name: 'Qwen2.5 72B Instruct',
    publisher: 'Alibaba Qwen',
    totalParamsB: 72,
    activeParamsB: 72,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['bartowski/Qwen2.5-72B-Instruct-GGUF'],
    license: 'Qwen License',
    notes: 'Denso da 72B, forte in matematica e multilingua.',
    sizeClass: 'grande',
    tags: ['general', 'multilingual'],
  },

  // ---------------------------------------------------------------------
  // Medi (14-70B) — entrano in RAM su una macchina ben equipaggiata
  // ---------------------------------------------------------------------
  {
    id: 'qwen3-32b',
    name: 'Qwen3 32B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 32,
    activeParamsB: 32,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/Qwen3-32B-GGUF', 'bartowski/Qwen_Qwen3-32B-GGUF'],
    license: 'Apache 2.0',
    notes: 'Denso da 32B con ragionamento commutabile. Circa 20 GB in Q4.',
    sizeClass: 'medio',
    tags: ['reasoning', 'general'],
  },
  {
    id: 'olmo-2-32b',
    name: 'OLMo 2 32B Instruct',
    publisher: 'Allen AI',
    totalParamsB: 32,
    activeParamsB: 32,
    architecture: 'dense',
    contextLength: 4096,
    ggufRepos: ['unsloth/OLMo-2-0325-32B-Instruct-GGUF', 'allenai/OLMo-2-0325-32B-Instruct-GGUF'],
    license: 'Apache 2.0',
    notes: 'Completamente aperto: pesi, dati e ricette di training pubblicati.',
    sizeClass: 'medio',
    tags: ['open-data', 'research'],
  },
  {
    id: 'qwen3-30b-a3b',
    name: 'Qwen3 30B A3B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 30,
    activeParamsB: 3,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/Qwen3-30B-A3B-GGUF', 'bartowski/Qwen_Qwen3-30B-A3B-GGUF'],
    license: 'Apache 2.0',
    notes: 'Piccolo abbastanza da provare la pipeline end-to-end prima di scaricare centinaia di GB.',
    sizeClass: 'medio',
    tags: ['efficient', 'reasoning'],
  },
  {
    id: 'gemma-3-27b',
    name: 'Gemma 3 27B',
    publisher: 'Google',
    totalParamsB: 27,
    activeParamsB: 27,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/gemma-3-27b-it-GGUF', 'bartowski/google_gemma-3-27b-it-GGUF'],
    license: 'Gemma Terms',
    notes: 'Multimodale (testo e immagini), ottimo rapporto qualità/dimensione.',
    sizeClass: 'medio',
    tags: ['multimodal', 'multilingual'],
  },
  {
    id: 'mistral-small-3.2',
    name: 'Mistral Small 3.2 24B',
    publisher: 'Mistral AI',
    totalParamsB: 24,
    activeParamsB: 24,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/Mistral-Small-3.2-24B-Instruct-2506-GGUF'],
    license: 'Apache 2.0',
    notes: 'Multimodale e sotto Apache 2.0: gira su una singola GPU da 16 GB in Q4.',
    sizeClass: 'medio',
    tags: ['multimodal', 'general'],
  },
  {
    id: 'devstral-small',
    name: 'Devstral Small 2507',
    publisher: 'Mistral AI',
    totalParamsB: 24,
    activeParamsB: 24,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/Devstral-Small-2507-GGUF'],
    license: 'Apache 2.0',
    notes: 'Specializzato in agenti di codice: pensato per girare in locale su una GPU.',
    sizeClass: 'medio',
    tags: ['coding', 'agentic'],
  },
  {
    id: 'gpt-oss-20b',
    name: 'gpt-oss 20B',
    publisher: 'OpenAI',
    totalParamsB: 21,
    activeParamsB: 3.6,
    architecture: 'moe',
    contextLength: 131072,
    ggufRepos: ['unsloth/gpt-oss-20b-GGUF', 'ggml-org/gpt-oss-20b-GGUF'],
    license: 'Apache 2.0',
    notes: '3.6B attivi: veloce anche su hardware modesto, con ragionamento regolabile.',
    sizeClass: 'medio',
    tags: ['reasoning', 'efficient'],
  },
  {
    id: 'phi-4',
    name: 'Phi 4 14B',
    publisher: 'Microsoft',
    totalParamsB: 14,
    activeParamsB: 14,
    architecture: 'dense',
    contextLength: 16384,
    ggufRepos: ['unsloth/phi-4-GGUF', 'bartowski/phi-4-GGUF'],
    license: 'MIT',
    notes: 'Denso da 14B molto forte in matematica e logica per la sua taglia.',
    sizeClass: 'medio',
    tags: ['reasoning', 'math'],
  },
  {
    id: 'qwen3-14b',
    name: 'Qwen3 14B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 14,
    activeParamsB: 14,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/Qwen3-14B-GGUF', 'bartowski/Qwen_Qwen3-14B-GGUF'],
    license: 'Apache 2.0',
    notes: 'Circa 9 GB in Q4: sta in VRAM su una scheda da 12 GB.',
    sizeClass: 'medio',
    tags: ['reasoning', 'general'],
  },

  // ---------------------------------------------------------------------
  // Piccoli (< 14B) — per provare la pipeline e per hardware modesto
  // ---------------------------------------------------------------------
  {
    id: 'gemma-3-12b',
    name: 'Gemma 3 12B',
    publisher: 'Google',
    totalParamsB: 12,
    activeParamsB: 12,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/gemma-3-12b-it-GGUF', 'bartowski/google_gemma-3-12b-it-GGUF'],
    license: 'Gemma Terms',
    notes: 'Multimodale, buon compromesso per una GPU da 12 GB.',
    sizeClass: 'piccolo',
    tags: ['multimodal', 'multilingual'],
  },
  {
    id: 'qwen3-8b',
    name: 'Qwen3 8B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 8,
    activeParamsB: 8,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/Qwen3-8B-GGUF', 'bartowski/Qwen_Qwen3-8B-GGUF'],
    license: 'Apache 2.0',
    notes: 'Circa 5 GB in Q4: gira comodamente in VRAM con contesto ampio.',
    sizeClass: 'piccolo',
    tags: ['reasoning', 'general'],
  },
  {
    id: 'llama-3.1-8b',
    name: 'Llama 3.1 8B Instruct',
    publisher: 'Meta',
    totalParamsB: 8,
    activeParamsB: 8,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['bartowski/Meta-Llama-3.1-8B-Instruct-GGUF', 'lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF'],
    license: 'Llama 3.1 Community',
    notes: 'Il riferimento più diffuso della fascia 8B, con enorme ecosistema di fine-tuning.',
    sizeClass: 'piccolo',
    tags: ['general'],
  },
  {
    id: 'ministral-8b',
    name: 'Ministral 8B 2410',
    publisher: 'Mistral AI',
    totalParamsB: 8,
    activeParamsB: 8,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['bartowski/Ministral-8B-Instruct-2410-GGUF'],
    license: 'Mistral Research',
    notes: 'Progettato per esecuzione locale e su dispositivi edge.',
    sizeClass: 'piccolo',
    tags: ['efficient'],
  },
  {
    id: 'gemma-3-4b',
    name: 'Gemma 3 4B',
    publisher: 'Google',
    totalParamsB: 4,
    activeParamsB: 4,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/gemma-3-4b-it-GGUF', 'bartowski/google_gemma-3-4b-it-GGUF'],
    license: 'Gemma Terms',
    notes: 'Multimodale in poco più di 2 GB: adatto anche senza GPU dedicata.',
    sizeClass: 'piccolo',
    tags: ['multimodal', 'efficient'],
  },
  {
    id: 'qwen3-4b',
    name: 'Qwen3 4B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 4,
    activeParamsB: 4,
    architecture: 'dense',
    contextLength: 131072,
    ggufRepos: ['unsloth/Qwen3-4B-GGUF', 'bartowski/Qwen_Qwen3-4B-GGUF'],
    license: 'Apache 2.0',
    notes: 'Sorprendentemente capace per 2.5 GB, con ragionamento incluso.',
    sizeClass: 'piccolo',
    tags: ['reasoning', 'efficient'],
  },
  {
    id: 'qwen3-1.7b',
    name: 'Qwen3 1.7B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 1.7,
    activeParamsB: 1.7,
    architecture: 'dense',
    contextLength: 32768,
    ggufRepos: ['unsloth/Qwen3-1.7B-GGUF', 'bartowski/Qwen_Qwen3-1.7B-GGUF'],
    license: 'Apache 2.0',
    notes: 'Circa 1 GB: ideale per verificare che motore, API e pipeline funzionino.',
    sizeClass: 'piccolo',
    tags: ['efficient', 'testing'],
  },
  {
    id: 'qwen3-0.6b',
    name: 'Qwen3 0.6B',
    publisher: 'Alibaba Qwen',
    totalParamsB: 0.6,
    activeParamsB: 0.6,
    architecture: 'dense',
    contextLength: 32768,
    ggufRepos: ['unsloth/Qwen3-0.6B-GGUF', 'bartowski/Qwen_Qwen3-0.6B-GGUF'],
    license: 'Apache 2.0',
    notes: 'Il più piccolo del catalogo: scarica in pochi secondi, utile solo per collaudo.',
    sizeClass: 'piccolo',
    tags: ['testing'],
  },
];

export const SIZE_CLASS_ORDER: SizeClass[] = ['gigante', 'grande', 'medio', 'piccolo'];

/** Effective bits per weight for the common GGUF quantisation schemes. */
export const QUANT_BITS: Record<string, number> = {
  F32: 32,
  F16: 16,
  BF16: 16,
  Q8_0: 8.5,
  Q6_K: 6.56,
  Q5_K_M: 5.67,
  Q5_K_S: 5.52,
  Q5_0: 5.5,
  Q4_K_M: 4.83,
  Q4_K_S: 4.57,
  Q4_0: 4.55,
  IQ4_XS: 4.25,
  Q3_K_M: 3.91,
  Q3_K_S: 3.5,
  IQ3_XXS: 3.06,
  Q2_K: 2.96,
  IQ2_XXS: 2.06,
  IQ1_M: 1.75,
};

/** Bytes on disk for a parameter count at a given quantisation. */
export function estimateWeightBytes(paramsBillions: number, quantization: string): number {
  const bits = QUANT_BITS[quantization.toUpperCase()] ?? QUANT_BITS.Q4_K_M;
  return (paramsBillions * 1e9 * bits) / 8;
}

export function findCatalogEntry(id: string): CatalogEntry | undefined {
  return MODEL_CATALOG.find((entry) => entry.id === id);
}
